.github/workflows/go.yml

Add pull request as pipeline trigger
List and link all the issues addressed by this PR.

chore: add pull_request as pipeline trigger

---

model/base.go
model/cdm_base.schema_v0.9.0.json
model/convert.go
model/convert_test.go
model/generator.go
model/model.go

- Updated to base schema v0.9.0
- Handling of discovery for derived/extended schema

fix: adapt SDK model package for extended asset link

---

README.md
cmd/al-ctl/cmd/test/test.go
cmd/al-ctl/internal/test/api-test.go
cmd/al-ctl/internal/test/asset-validation.go

add support for validation if link-ml is already supported in the testing environments.
add support for validation if link-ml is already supported in the testing environments.

Feat: add option for asset validation when python is supported

---

model/nameplate.go
model/nameplate_test.go

Inserts an explicit field for the IDLink into the provided schema.

Feat: Add support for IDLink field

---

README.md
REUSE.toml
cmd/al-ctl/cmd/test/test.go
cmd/al-ctl/internal/test/models.go
cmd/al-ctl/internal/test/registration.go
cmd/al-ctl/internal/test/registry.go
registry.json

Tests are added to verify asset link registration on grpc-server-registry

Feat: Add test for asset link registration

---

README.md
cdm-al-reference/reference/reference.go
cmd/al-ctl/cmd/discovery/discover.go
cmd/al-ctl/cmd/root.go
cmd/al-ctl/cmd/test/test.go
cmd/al-ctl/internal/al/discovery.go
cmd/al-ctl/internal/shared/shared.go
cmd/al-ctl/internal/test/api-test.go
cmd/al-ctl/internal/test/asset-validation.go
cmd/al-ctl/internal/test/discovery.go

Added the provision to validate cancellation of discovery in the test suite

Feat: Add test for discovery cancellation

---

model/convert-from-discovered-device.go
model/convert-from-discovered-device_test.go
model/convert-to-discovered-device_test.go
model/convert_e2e_test.go
model/model.go
model/model_test.go

add context with latest base schema version in device model
https://github.com/industrial-asset-hub/asset-link-sdk/issues/63

fix(model): add context in device model

---

.github/actions/prepare/action.yml
.github/workflows/go.yml
.goreleaser.yaml

generate cyclonedx SBOM in workflow 
generate cyclonedx SBOM in workflow

Chore/ generate cyclonedx SBOM

---

.github/workflows/go.yml
.goreleaser.yaml

generated SBOM will be released in the assets 

fix: fix sbom release 

---

.goreleaser.yaml
cdm-al-reference/Dockerfile
cdm-al-reference/docker-compose.yml
cookiecutter-project-template/{{ cookiecutter.al_project }}/.goreleaser.yaml
registry/docker-compose.yml

- adjust GoReleaser config to create a container image of the reference asset link
- add docker-compose config for registry and reference asset link
- tag images with latest in addition to version
- fix architecture typo
none

feat: create container image of reference asset link

---

.goreleaser.yaml
cookiecutter-project-template/{{ cookiecutter.al_project }}/.goreleaser.yaml

Update GoReleaser configuration files for SDK and Asset Link template to avoid usage of deprecated options.
none

chore: update GoReleaser configs

---

docs/bootstrap.md

Improvement in documentation, for the scenario when asset-gateway is running via docker-compose and asset-link in host machine.
add missing information of asset-link run config in docs for a scenario.
- [x ] This change requires a documentation update
- [x ] I have read the [CONTRIBUTING](../CONTRIBUTING.md) document.
- [x ] My changes adhere to the established code style, patterns, and best practices.
- [x ] I have added tests that demonstrate the effectiveness of my changes.
- [x ] I have updated the documentation accordingly (if applicable).

docs(bootstrap): eg config registry in docker

---

model/convert-to-discovered-device_test.go
model/helper.go
model/model.go
model/nameplate.go
model/nameplate_test.go

The management_state and ID being required properties are added in the software_component
So that schema-validation in CDM-UI does not fail for discovered assets
Management_state and ID were missing in software_component of discovered asset

fix: add management_state and Id in software component

---

docs/bootstrap.md
docs/cmd.md
docs/observability.md
docs/overview.md

Use consistent upper-case spelling for "Asset Link(s)".
List and link all the issues addressed by this PR.

docs: use consistent spelling

---

docs/bootstrap.md
docs/observability.md
docs/overview.md

Improvements in documentation is done for the below points identified.
1. For observability webserver documentation, a dot (.) is missing at the end of the paragraph
2. Spell and grammar check for overview documentation

fix: improve documentation for spell and grammar check

---

cmd/al-ctl/cmd/test/test.go
cmd/al-ctl/internal/test/api-test.go
cmd/al-ctl/internal/test/discovery.go
cmd/al-ctl/internal/test/identifiers.go
docs/cmd.md

This PR adds new API tests regarding "GetIdentifiers" to existing API tests.
none

test: add get identifiers api tests

---

.github/workflows/go.yml
.golangci.yml
cookiecutter-project-template/{{ cookiecutter.al_project }}/.golangci.yml
docs/overview.md
go.mod

Updated golang version to 1.24.6
1. Previous golang version 1.23 is end of life
- [X ] I have read the [CONTRIBUTING](../CONTRIBUTING.md) document.
- [X ] My changes adhere to the established code style, patterns, and best practices.

chore: updated golang version to 1.24.6

---

internal/registryclient/registryclient.go

Added driver info app type for the sdk

feat: add driverinfo app type for sdk

---

cookiecutter-project-template/{{ cookiecutter.al_project }}/testscripts/validate-asset.sh
docs/cmd.md
model/base.go
model/cdm_base.schema_v0.12.0.json
model/convert-to-discovered-device_test.go
model/convert_e2e_test.go
model/generator.go
model/iah_base_v0.12.0.yaml
model/model.go
model/model_test.go

Updated base schema version 0.12.0

chore: updated the base schema version v0.12.0

---

assetlink/al.go
internal/registryclient/registryclient.go

This MR moves registration of the available interfaces to the location where the instance is initiated.
Please provide a concise summary of the changes and their motivation.
List and link all the issues addressed by this PR.

refactor: make interface registration dynamic
